name: ForceItemBattleChallenge
version: '${project.version}'
main: de.janhck.forceitembattlechallenge.ForceItemBattleChallenge
api-version: '1.20'
commands:
  start:
  skip:
  stopGame:
  pause:
    permission: battle.forceitem.command.admin
